"""Database of 50+ ragas with authentic aroha/avaroha, vadi/samvadi, mood, and time.

Each raga entry follows traditional Hindustani classical music theory.
Notation: uppercase = shuddha, lowercase = komal, Ma' = tivra Ma.
"""

from __future__ import annotations

from raga.models import RagaDefinition

# fmt: off
_RAGA_DATA: list[dict] = [
    # ── Kalyan Thaat ──
    {
        "name": "yaman",
        "thaat": "kalyan",
        "aroha": ["Sa", "Re", "Ga", "Ma'", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ga", "Re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Ni",
        "pakad": ["Ni", "Re", "Ga", "Re", "Sa"],
        "mood": "devotional, serene, romantic",
        "time": "evening, 1st prahar of night",
        "jati": "sampurna-sampurna",
        "description": "One of the most fundamental ragas, often first taught to students.",
    },
    {
        "name": "yaman_kalyan",
        "thaat": "kalyan",
        "aroha": ["Sa", "Re", "Ga", "Ma'", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ga", "Ma", "Re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Ni",
        "pakad": ["Ga", "Ma", "Re", "Sa", "Ni", "Re", "Ga"],
        "mood": "serene, devotional",
        "time": "evening, 1st prahar of night",
        "jati": "sampurna-sampurna",
        "description": "Uses both shuddha Ma and tivra Ma; shuddha Ma only in descent.",
    },
    {
        "name": "shudh_kalyan",
        "thaat": "kalyan",
        "aroha": ["Sa", "Re", "Ga", "Ma'", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Sa",
        "pakad": ["Pa", "Ga", "Ma'", "Pa", "Dha", "Pa"],
        "mood": "calm, meditative",
        "time": "late evening",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "hameer",
        "thaat": "kalyan",
        "aroha": ["Sa", "Re", "Ga", "Ma'", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Dha",
        "samvadi": "Ga",
        "pakad": ["Dha", "Ma'", "Pa", "Dha", "Sa*", "Ni", "Dha", "Pa"],
        "mood": "majestic, serious",
        "time": "late night, 2nd prahar",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "kedar",
        "thaat": "kalyan",
        "aroha": ["Sa", "Ma", "Ma'", "Pa", "Dha", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "Ma'", "Pa", "Dha", "Pa", "Ma'", "Ma", "Re", "Sa"],
        "mood": "devotional, peaceful",
        "time": "late evening",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Re", "Ga"],
    },
    # ── Bilawal Thaat ──
    {
        "name": "bilawal",
        "thaat": "bilawal",
        "aroha": ["Sa", "Re", "Ga", "Ma", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Dha",
        "samvadi": "Ga",
        "pakad": ["Dha", "Pa", "Ga", "Ma", "Re", "Sa"],
        "mood": "happy, auspicious",
        "time": "morning, late morning",
        "jati": "sampurna-sampurna",
        "description": "The parent thaat equivalent to the Western major scale.",
    },
    {
        "name": "alhaiya_bilawal",
        "thaat": "bilawal",
        "aroha": ["Sa", "Re", "Ga", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Dha",
        "samvadi": "Ga",
        "pakad": ["Ga", "Pa", "Dha", "Pa", "Ga", "Ma", "Re", "Sa"],
        "mood": "joyful, bright",
        "time": "morning",
        "jati": "shadav-sampurna",
        "varjit_aroha": ["Ma"],
    },
    {
        "name": "durga",
        "thaat": "bilawal",
        "aroha": ["Sa", "Re", "Ma", "Pa", "Dha", "Sa*"],
        "avaroha": ["Sa*", "Dha", "Pa", "Ma", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "Re", "Sa", "Dha", "Pa", "Ma", "Re", "Sa"],
        "mood": "valiant, bright",
        "time": "late evening",
        "jati": "audav-audav",
        "varjit_aroha": ["Ga", "Ni"],
        "varjit_avaroha": ["Ga", "Ni"],
    },
    {
        "name": "bihag",
        "thaat": "bilawal",
        "aroha": ["Sa", "Ga", "Ma", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ga", "Ma", "Pa", "Ni", "Pa", "Dha", "Pa", "Ma", "Ga"],
        "mood": "romantic, light",
        "time": "late night",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Re", "Dha"],
    },
    # ── Khamaj Thaat ──
    {
        "name": "khamaj",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ga", "Ma", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Ni",
        "pakad": ["Ga", "Ma", "Pa", "Dha", "ni", "Dha", "Pa"],
        "mood": "romantic, erotic",
        "time": "late night",
        "jati": "sampurna-sampurna",
        "description": "Uses shuddha Ni in aroha and komal Ni in avaroha.",
    },
    {
        "name": "des",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ma", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Re", "Ma", "Pa", "ni", "Dha", "Pa"],
        "mood": "romantic, light",
        "time": "late night",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Ga", "Dha"],
    },
    {
        "name": "tilak_kamod",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ga", "Pa", "Dha", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ga", "Ma", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Re", "Ga", "Re", "Sa", "Pa", "Ga", "Re"],
        "mood": "romantic, joyful",
        "time": "late evening",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Ma", "Ni"],
    },
    {
        "name": "jhinjhoti",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ga", "Ma", "Pa", "Dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Dha",
        "samvadi": "Ga",
        "pakad": ["Dha", "ni", "Dha", "Pa", "Ma", "Ga", "Re"],
        "mood": "light, romantic",
        "time": "late night",
        "jati": "sampurna-sampurna",
    },
    # ── Bhairav Thaat ──
    {
        "name": "bhairav",
        "thaat": "bhairav",
        "aroha": ["Sa", "re", "Ga", "Ma", "Pa", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma", "Ga", "re", "Sa"],
        "vadi": "Dha",
        "samvadi": "Re",
        "pakad": ["Ga", "Ma", "dha", "Ma", "Pa", "Ga", "Ma", "re", "Sa"],
        "mood": "serious, devotional, majestic",
        "time": "early morning, sandhiprakash",
        "jati": "sampurna-sampurna",
        "description": "Early morning raga with a profound, meditative quality.",
    },
    {
        "name": "ahir_bhairav",
        "thaat": "bhairav",
        "aroha": ["Sa", "re", "Ga", "Ma", "Pa", "Dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "Ga", "re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "Ga", "re", "Sa", "ni", "Dha", "Pa"],
        "mood": "devotional, serene",
        "time": "early morning",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "nat_bhairav",
        "thaat": "bhairav",
        "aroha": ["Sa", "Re", "Ga", "Ma", "Pa", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Sa",
        "pakad": ["Pa", "dha", "Pa", "Ga", "Ma", "Re", "Sa"],
        "mood": "regal, festive",
        "time": "morning",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "jogiya",
        "thaat": "bhairav",
        "aroha": ["Sa", "re", "Ma", "Pa", "dha", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma", "re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["re", "Ma", "Pa", "dha", "Pa", "Ma", "re", "Sa"],
        "mood": "ascetic, devotional",
        "time": "early morning",
        "jati": "audav-shadav",
        "varjit_aroha": ["Ga", "Ni"],
        "varjit_avaroha": ["Ga"],
    },
    # ── Bhairavi Thaat ──
    {
        "name": "bhairavi",
        "thaat": "bhairavi",
        "aroha": ["Sa", "re", "ga", "Ma", "Pa", "dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Pa", "Ma", "ga", "re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "Pa", "dha", "Ma", "Pa", "ga", "Ma", "re", "Sa"],
        "mood": "devotional, compassionate, morning farewell",
        "time": "early morning; also conclusion of concerts",
        "jati": "sampurna-sampurna",
        "description": "Queen of ragas. Can use all 12 notes as embellishments.",
    },
    {
        "name": "malkauns",
        "thaat": "bhairavi",
        "aroha": ["Sa", "ga", "Ma", "dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Ma", "ga", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "dha", "ni", "dha", "Ma", "ga", "Ma", "ga", "Sa"],
        "mood": "serious, meditative, profound",
        "time": "midnight, 3rd prahar of night",
        "jati": "audav-audav",
        "varjit_aroha": ["Re", "Pa"],
        "varjit_avaroha": ["Re", "Pa"],
    },
    {
        "name": "bilaskhani_todi",
        "thaat": "bhairavi",
        "aroha": ["Sa", "re", "ga", "Ma", "Pa", "dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Pa", "Ma", "ga", "re", "Sa"],
        "vadi": "dha",
        "samvadi": "ga",
        "pakad": ["dha", "ni", "dha", "Pa", "Ma", "ga", "re", "Sa"],
        "mood": "pathos, melancholy",
        "time": "morning",
        "jati": "sampurna-sampurna",
    },
    # ── Todi Thaat ──
    {
        "name": "todi",
        "thaat": "todi",
        "aroha": ["Sa", "re", "ga", "Ma'", "Pa", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma'", "ga", "re", "Sa"],
        "vadi": "dha",
        "samvadi": "ga",
        "pakad": ["re", "ga", "re", "Sa", "dha", "Ni", "dha", "Pa", "Ma'", "ga"],
        "mood": "intense, serious, longing",
        "time": "late morning",
        "jati": "sampurna-sampurna",
        "description": "Uses komal Re, komal Ga, tivra Ma, komal Dha with shuddha Ni.",
    },
    {
        "name": "multani",
        "thaat": "todi",
        "aroha": ["Sa", "ga", "Ma'", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma'", "ga", "re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Sa",
        "pakad": ["Pa", "Ni", "dha", "Pa", "Ma'", "ga", "re", "ga", "Sa"],
        "mood": "longing, meditative",
        "time": "afternoon",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Re", "Dha"],
    },
    {
        "name": "gurjari_todi",
        "thaat": "todi",
        "aroha": ["Sa", "re", "ga", "Ma'", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Ma'", "ga", "re", "Sa"],
        "vadi": "re",
        "samvadi": "dha",
        "pakad": ["re", "ga", "re", "Sa", "dha", "Ni", "dha"],
        "mood": "serious, contemplative",
        "time": "late morning",
        "jati": "shadav-shadav",
        "varjit_aroha": ["Pa"],
        "varjit_avaroha": ["Pa"],
    },
    # ── Asavari Thaat ──
    {
        "name": "asavari",
        "thaat": "asavari",
        "aroha": ["Sa", "Re", "Ma", "Pa", "dha", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "dha",
        "samvadi": "ga",
        "pakad": ["dha", "Ma", "Pa", "dha", "Ma", "ga", "Re", "Sa"],
        "mood": "pathos, serious, vairagy",
        "time": "late morning",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Ga", "Ni"],
    },
    {
        "name": "darbari_kanada",
        "thaat": "asavari",
        "aroha": ["Sa", "Re", "ga", "Ma", "Pa", "dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Ma", "Re", "ga", "Re", "Sa", "dha", "ni", "dha", "Pa"],
        "mood": "majestic, grand, serious",
        "time": "midnight, 3rd prahar",
        "jati": "sampurna-sampurna",
        "description": "Associated with the court of Akbar. Distinctive komal Ga andolan.",
    },
    {
        "name": "adana",
        "thaat": "asavari",
        "aroha": ["Sa", "Re", "Ma", "Pa", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Sa",
        "pakad": ["Pa", "ni", "dha", "Pa", "Ma", "Re", "ga", "Re", "Sa"],
        "mood": "serious, heroic",
        "time": "late night",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Ga", "Dha"],
    },
    {
        "name": "jaunpuri",
        "thaat": "asavari",
        "aroha": ["Sa", "Re", "ga", "Ma", "Pa", "dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "dha",
        "samvadi": "ga",
        "pakad": ["ga", "Ma", "Re", "Sa", "dha", "ni", "dha", "Pa"],
        "mood": "pensive, gentle",
        "time": "late morning, afternoon",
        "jati": "sampurna-sampurna",
    },
    # ── Marwa Thaat ──
    {
        "name": "marwa",
        "thaat": "marwa",
        "aroha": ["Sa", "re", "Ga", "Ma'", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Ma'", "Ga", "re", "Sa"],
        "vadi": "Dha",
        "samvadi": "Ga",
        "pakad": ["Dha", "Ni", "Dha", "Ma'", "Ga", "re", "Ga", "re", "Sa"],
        "mood": "serious, restless, profound",
        "time": "evening, sandhiprakash",
        "jati": "shadav-shadav",
        "varjit_aroha": ["Pa"],
        "varjit_avaroha": ["Pa"],
    },
    {
        "name": "puriya",
        "thaat": "marwa",
        "aroha": ["Sa", "re", "Ga", "Ma'", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Ma'", "Ga", "re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Ni",
        "pakad": ["Ga", "Ma'", "Dha", "Ni", "Dha", "Ma'", "Ga", "re", "Sa"],
        "mood": "intense, meditative",
        "time": "evening, sandhiprakash",
        "jati": "shadav-shadav",
        "varjit_aroha": ["Pa"],
        "varjit_avaroha": ["Pa"],
    },
    {
        "name": "puriya_dhanashree",
        "thaat": "marwa",
        "aroha": ["Sa", "re", "Ga", "Ma'", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ga", "re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Sa",
        "pakad": ["Ga", "Ma'", "Pa", "Ga", "Ma'", "re", "Sa", "Ni", "re", "Sa"],
        "mood": "enchanting, soothing",
        "time": "early evening",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "sohni",
        "thaat": "marwa",
        "aroha": ["Sa", "Re", "Ga", "Ma'", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ga", "Re", "Sa"],
        "vadi": "Dha",
        "samvadi": "Ga",
        "pakad": ["Dha", "Ni", "Dha", "Ma'", "Ga", "Re"],
        "mood": "romantic, elegant",
        "time": "late night",
        "jati": "shadav-sampurna",
        "varjit_aroha": ["Pa"],
    },
    # ── Poorvi Thaat ──
    {
        "name": "poorvi",
        "thaat": "poorvi",
        "aroha": ["Sa", "re", "Ga", "Ma'", "Pa", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma'", "Ga", "re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Ni",
        "pakad": ["Ga", "Ma'", "dha", "Ma'", "Pa", "Ga", "re", "Sa"],
        "mood": "serious, contemplative",
        "time": "evening, sandhiprakash",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "puriya_kalyan",
        "thaat": "poorvi",
        "aroha": ["Sa", "re", "Ga", "Ma'", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma'", "Ga", "re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Re",
        "pakad": ["re", "Ga", "Ma'", "Pa", "Ni", "Dha", "Pa"],
        "mood": "meditative, tranquil",
        "time": "early evening",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "shree",
        "thaat": "poorvi",
        "aroha": ["Sa", "re", "Ma'", "Pa", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma'", "Ga", "re", "Sa"],
        "vadi": "re",
        "samvadi": "Pa",
        "pakad": ["re", "Ma'", "Pa", "dha", "Pa", "Ni", "dha", "Pa"],
        "mood": "regal, serious, grand",
        "time": "evening",
        "jati": "shadav-sampurna",
        "varjit_aroha": ["Ga"],
    },
    {
        "name": "basant",
        "thaat": "poorvi",
        "aroha": ["Sa", "Ga", "Ma'", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma'", "Ga", "re", "Sa"],
        "vadi": "dha",
        "samvadi": "Re",
        "pakad": ["dha", "Ni", "Sa*", "Ni", "dha", "Ma'", "Ga", "re", "Sa"],
        "mood": "joyful, spring",
        "time": "late night",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Re", "Pa"],
    },
    # ── Kafi Thaat ──
    {
        "name": "kafi",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "ga", "Ma", "Pa", "Dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Sa",
        "pakad": ["Pa", "ga", "Ma", "Re", "Sa", "ga", "Re"],
        "mood": "romantic, light",
        "time": "midnight to morning",
        "jati": "sampurna-sampurna",
        "description": "Uses komal Ga and komal Ni. Foundation for many folk melodies.",
    },
    {
        "name": "bageshree",
        "thaat": "kafi",
        "aroha": ["Sa", "ga", "Ma", "Dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Ma", "Pa", "Dha", "Ma", "ga", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "Dha", "ni", "Dha", "Ma", "ga", "Re", "Sa"],
        "mood": "romantic, emotional",
        "time": "2nd prahar of night",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Re", "Pa"],
    },
    {
        "name": "bhimpalasi",
        "thaat": "kafi",
        "aroha": ["Sa", "ga", "Ma", "Pa", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "Pa", "ga", "Ma", "ga", "Re", "Sa"],
        "mood": "shringaar, tender",
        "time": "afternoon, 2nd prahar",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Re", "Dha"],
    },
    {
        "name": "pilu",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "ga", "Ma", "Pa", "Dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Ni",
        "pakad": ["ga", "Ma", "Pa", "ga", "Ma", "Re", "Sa"],
        "mood": "light, playful, romantic",
        "time": "flexible, often conclusion",
        "jati": "sampurna-sampurna",
        "description": "A mishra raga allowing many liberties with additional notes.",
    },
    {
        "name": "dhanashree",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "ga", "Ma", "Pa", "Dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "ga", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Re", "Ma", "Pa", "Dha", "ni", "Pa"],
        "mood": "joyful, devotional",
        "time": "evening",
        "jati": "sampurna-sampurna",
    },
    # ── Additional important ragas ──
    {
        "name": "miyan_ki_todi",
        "thaat": "todi",
        "aroha": ["Sa", "re", "ga", "Ma'", "Pa", "dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma'", "ga", "re", "Sa"],
        "vadi": "dha",
        "samvadi": "ga",
        "pakad": ["dha", "Ni", "Sa*", "re", "ga", "re", "Sa"],
        "mood": "intense, profound",
        "time": "morning",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "rageshree",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ga", "Ma", "Pa", "Dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Ma", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Re",
        "pakad": ["Pa", "Dha", "Ma", "Pa", "Ga", "Ma", "Re", "Ga", "Re"],
        "mood": "romantic, late night",
        "time": "2nd prahar of night",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "hamsadhwani",
        "thaat": "bilawal",
        "aroha": ["Sa", "Re", "Ga", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Pa", "Ga", "Re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Ni",
        "pakad": ["Ga", "Pa", "Ni", "Pa", "Ga", "Re", "Sa"],
        "mood": "auspicious, bright, joyful",
        "time": "evening",
        "jati": "audav-audav",
        "varjit_aroha": ["Ma", "Dha"],
        "varjit_avaroha": ["Ma", "Dha"],
        "description": "Popular Carnatic raga widely used in Hindustani music too.",
    },
    {
        "name": "chandrakauns",
        "thaat": "bhairavi",
        "aroha": ["Sa", "ga", "Ma", "dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Ma", "ga", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Ma", "dha", "ni", "dha", "Ma", "ga", "Sa"],
        "mood": "mysterious, romantic",
        "time": "midnight",
        "jati": "audav-audav",
        "varjit_aroha": ["Re", "Pa"],
        "varjit_avaroha": ["Re", "Pa"],
    },
    {
        "name": "shivaranjani",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "ga", "Pa", "Dha", "Sa*"],
        "avaroha": ["Sa*", "Dha", "Pa", "ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Re",
        "pakad": ["Pa", "Dha", "Pa", "ga", "Re", "Sa"],
        "mood": "serene, devotional",
        "time": "evening",
        "jati": "audav-audav",
        "varjit_aroha": ["Ma", "Ni"],
        "varjit_avaroha": ["Ma", "Ni"],
    },
    {
        "name": "charukeshi",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ga", "Ma", "Pa", "dha", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Sa",
        "pakad": ["Pa", "dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "mood": "serene, contemplative",
        "time": "evening",
        "jati": "sampurna-sampurna",
    },
    {
        "name": "madhuvanti",
        "thaat": "todi",
        "aroha": ["Sa", "ga", "Ma'", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "dha", "Pa", "Ma'", "ga", "Re", "Sa"],
        "vadi": "Ma'",
        "samvadi": "Sa",
        "pakad": ["ga", "Ma'", "Pa", "Ni", "Pa", "Ma'", "ga", "Re"],
        "mood": "romantic, sweet",
        "time": "afternoon",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Re", "Dha"],
    },
    {
        "name": "miyan_ki_malhar",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "Ma", "Pa", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "Re", "ga", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Re", "Ma", "Pa", "ni", "Pa", "Dha", "Pa", "Ma", "Re", "ga", "Re"],
        "mood": "rain, romantic, monsoon",
        "time": "monsoon season",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Ga", "Dha"],
    },
    {
        "name": "megh",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "Ma", "Pa", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Pa", "Ma", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Re", "Ma", "Pa", "ni", "Pa", "Ma", "Re", "Sa"],
        "mood": "majestic, rain-invoking",
        "time": "monsoon, 2nd prahar",
        "jati": "audav-audav",
        "varjit_aroha": ["Ga", "Dha"],
        "varjit_avaroha": ["Ga", "Dha"],
    },
    {
        "name": "sarang",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "Ma", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Pa", "Ma", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Re", "Ma", "Pa", "Ni", "Pa", "Ma", "Re", "Sa"],
        "mood": "bright, afternoon delight",
        "time": "afternoon",
        "jati": "audav-audav",
        "varjit_aroha": ["Ga", "Dha"],
        "varjit_avaroha": ["Ga", "Dha"],
    },
    {
        "name": "shankara",
        "thaat": "bilawal",
        "aroha": ["Sa", "Re", "Ga", "Pa", "Dha", "Sa*"],
        "avaroha": ["Sa*", "Dha", "Pa", "Ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Re",
        "pakad": ["Ga", "Pa", "Dha", "Pa", "Ga", "Re", "Sa"],
        "mood": "auspicious, noble",
        "time": "evening",
        "jati": "audav-audav",
        "varjit_aroha": ["Ma", "Ni"],
        "varjit_avaroha": ["Ma", "Ni"],
    },
    {
        "name": "kalavati",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ma", "Pa", "ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Pa", "Ma", "Re", "Sa"],
        "vadi": "Ma",
        "samvadi": "Sa",
        "pakad": ["Re", "Ma", "Pa", "ni", "Pa", "Ma", "Re"],
        "mood": "gentle, soothing",
        "time": "late night",
        "jati": "audav-audav",
        "varjit_aroha": ["Ga", "Dha"],
        "varjit_avaroha": ["Ga", "Dha"],
    },
    {
        "name": "hansdhwani",
        "thaat": "bilawal",
        "aroha": ["Sa", "Re", "Ga", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Pa", "Ga", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Ga", "Re", "Pa", "Ni", "Pa", "Ga", "Re"],
        "mood": "pleasant, joyful",
        "time": "any time, auspicious",
        "jati": "audav-audav",
        "varjit_aroha": ["Ma", "Dha"],
        "varjit_avaroha": ["Ma", "Dha"],
    },
    {
        "name": "bhoopali",
        "thaat": "kalyan",
        "aroha": ["Sa", "Re", "Ga", "Pa", "Dha", "Sa*"],
        "avaroha": ["Sa*", "Dha", "Pa", "Ga", "Re", "Sa"],
        "vadi": "Ga",
        "samvadi": "Dha",
        "pakad": ["Ga", "Re", "Pa", "Ga", "Dha", "Pa", "Ga"],
        "mood": "calm, devotional, pleasant",
        "time": "1st prahar of night",
        "jati": "audav-audav",
        "varjit_aroha": ["Ma", "Ni"],
        "varjit_avaroha": ["Ma", "Ni"],
        "description": "Pentatonic raga, known as Mohanam in Carnatic music.",
    },
    {
        "name": "desh",
        "thaat": "khamaj",
        "aroha": ["Sa", "Re", "Ma", "Pa", "Ni", "Sa*"],
        "avaroha": ["Sa*", "ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Re", "Ma", "Pa", "ni", "Dha", "Pa", "Ma", "Ga", "Re"],
        "mood": "patriotic, light, festive",
        "time": "2nd prahar of night",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Ga", "Dha"],
    },
    {
        "name": "brindavani_sarang",
        "thaat": "kafi",
        "aroha": ["Sa", "Re", "Ma", "Pa", "Dha", "Ni", "Sa*"],
        "avaroha": ["Sa*", "Ni", "Dha", "Pa", "Ma", "Re", "Sa"],
        "vadi": "Re",
        "samvadi": "Pa",
        "pakad": ["Re", "Ma", "Re", "Pa", "Dha", "Pa"],
        "mood": "joyful, romantic",
        "time": "afternoon",
        "jati": "shadav-shadav",
        "varjit_aroha": ["Ga"],
        "varjit_avaroha": ["Ga"],
    },
    {
        "name": "pahadi",
        "thaat": "bilawal",
        "aroha": ["Sa", "Re", "Ga", "Pa", "Dha", "Sa*"],
        "avaroha": ["Sa*", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
        "vadi": "Pa",
        "samvadi": "Re",
        "pakad": ["Pa", "Dha", "Sa*", "Dha", "Pa", "Ga", "Ma", "Re"],
        "mood": "light, folk, pastoral",
        "time": "late night",
        "jati": "audav-sampurna",
        "varjit_aroha": ["Ma", "Ni"],
    },
]
# fmt: on


class RagaDatabase:
    """Database of Indian classical ragas with lookup and search."""

    def __init__(self) -> None:
        self._ragas: dict[str, RagaDefinition] = {}
        for data in _RAGA_DATA:
            raga = RagaDefinition(**data)
            self._ragas[raga.name.lower()] = raga

    def get(self, name: str) -> RagaDefinition:
        """Get a raga by name (case-insensitive)."""
        key = name.lower().replace(" ", "_")
        if key not in self._ragas:
            raise KeyError(
                f"Raga '{name}' not found. Available: {', '.join(sorted(self._ragas))}"
            )
        return self._ragas[key]

    def search(self, **kwargs: str) -> list[RagaDefinition]:
        """Search ragas by attribute (thaat, mood, time, vadi, etc.)."""
        results = []
        for raga in self._ragas.values():
            match = True
            for key, value in kwargs.items():
                attr = getattr(raga, key, None)
                if attr is None:
                    match = False
                    break
                if isinstance(attr, str) and value.lower() not in attr.lower():
                    match = False
                    break
            if match:
                results.append(raga)
        return results

    def list_all(self) -> list[RagaDefinition]:
        """Return all ragas sorted by name."""
        return sorted(self._ragas.values(), key=lambda r: r.name)

    def list_names(self) -> list[str]:
        """Return sorted list of all raga names."""
        return sorted(self._ragas.keys())

    def by_thaat(self, thaat: str) -> list[RagaDefinition]:
        """Get all ragas belonging to a thaat."""
        return [r for r in self._ragas.values() if r.thaat.lower() == thaat.lower()]

    def by_time(self, time_keyword: str) -> list[RagaDefinition]:
        """Search ragas by performance time keyword."""
        return self.search(time=time_keyword)

    @property
    def count(self) -> int:
        return len(self._ragas)

    def get_allowed_swaras(self, name: str) -> set[str]:
        """Get the full set of swara notations allowed in a raga."""
        raga = self.get(name)
        swaras: set[str] = set()
        for note in raga.aroha + raga.avaroha:
            clean = note.rstrip("*").lstrip(".")
            swaras.add(clean)
        return swaras
